use super::webhook_handlers::utils::parse_webhook_payload;
use serde_json::Value;

pub const SKIP_NOTIFICATION_MARKER: &str = "[skip github-alerts]";

const IDENTITY_PATHS: &[&[&str]] = &[
    &["sender", "login"],
    &["actor", "login"],
    &["pusher", "name"],
    &["pull_request", "user", "login"],
    &["issue", "user", "login"],
    &["release", "author", "login"],
    &["workflow_run", "actor", "login"],
    &["workflow_run", "triggering_actor", "login"],
    &["check_run", "app", "slug"],
];

const BRANCH_PATHS: &[&[&str]] = &[
    &["ref"],
    &["pull_request", "head", "ref"],
    &["pull_request", "head", "label"],
    &["workflow_run", "head_branch"],
    &["check_run", "check_suite", "head_branch"],
];

/// Returns true for webhook activity generated by Dependabot or attached to a
/// `dependabot/*` branch. The branch rule also gives maintainers a predictable
/// way to perform manual dependency remediation without Telegram noise.
pub fn is_dependabot_event(body: &[u8]) -> bool {
    let Some(payload) = parse_payload(body) else {
        return false;
    };

    IDENTITY_PATHS
        .iter()
        .filter_map(|path| string_at_path(&payload, path))
        .any(is_dependabot_identity)
        || BRANCH_PATHS
            .iter()
            .filter_map(|path| string_at_path(&payload, path))
            .any(is_dependabot_branch)
}

/// Returns true when a push contains the explicit opt-out marker in any commit
/// message. This supports quiet, maintainer-authored dependency sweeps directly
/// on the default branch without guessing from filenames or package metadata.
pub fn has_skip_notification_marker(body: &[u8]) -> bool {
    let Some(payload) = parse_payload(body) else {
        return false;
    };

    string_at_path(&payload, &["head_commit", "message"]).is_some_and(contains_skip_marker)
        || payload
            .get("commits")
            .and_then(Value::as_array)
            .is_some_and(|commits| {
                commits.iter().any(|commit| {
                    commit
                        .get("message")
                        .and_then(Value::as_str)
                        .is_some_and(contains_skip_marker)
                })
            })
}

fn parse_payload(body: &[u8]) -> Option<Value> {
    parse_webhook_payload(body).ok()
}

fn string_at_path<'a>(payload: &'a Value, path: &[&str]) -> Option<&'a str> {
    path.iter()
        .try_fold(payload, |value, key| value.get(*key))?
        .as_str()
}

fn is_dependabot_identity(value: &str) -> bool {
    matches!(
        value.to_ascii_lowercase().as_str(),
        "dependabot" | "dependabot[bot]" | "dependabot-preview" | "dependabot-preview[bot]"
    )
}

fn is_dependabot_branch(value: &str) -> bool {
    let branch = value.strip_prefix("refs/heads/").unwrap_or(value);
    let branch = branch.split_once(':').map_or(branch, |(_, name)| name);

    branch == "dependabot" || branch.starts_with("dependabot/")
}

fn contains_skip_marker(message: &str) -> bool {
    message
        .to_ascii_lowercase()
        .contains(SKIP_NOTIFICATION_MARKER)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn payload(value: Value) -> Vec<u8> {
        serde_json::to_vec(&value).unwrap()
    }

    #[test]
    fn suppresses_dependabot_sender() {
        let body = payload(json!({"sender": {"login": "dependabot[bot]"}}));
        assert!(is_dependabot_event(&body));
    }

    #[test]
    fn suppresses_form_encoded_dependabot_sender() {
        let json = json!({"sender": {"login": "dependabot[bot]"}}).to_string();
        let body = serde_urlencoded::to_string([("payload", json)]).unwrap();
        assert!(is_dependabot_event(body.as_bytes()));
    }

    #[test]
    fn suppresses_legacy_dependabot_sender_case_insensitively() {
        let body = payload(json!({"sender": {"login": "Dependabot-Preview[bot]"}}));
        assert!(is_dependabot_event(&body));
    }

    #[test]
    fn suppresses_human_action_on_dependabot_pull_request() {
        let body = payload(json!({
            "sender": {"login": "maintainer"},
            "pull_request": {
                "user": {"login": "dependabot[bot]"},
                "head": {"ref": "dependabot/npm_and_yarn/example-1.2.3"}
            }
        }));
        assert!(is_dependabot_event(&body));
    }

    #[test]
    fn suppresses_manual_push_to_dependabot_branch() {
        let body = payload(json!({
            "sender": {"login": "maintainer"},
            "ref": "refs/heads/dependabot/security-alerts-2026-09"
        }));
        assert!(is_dependabot_event(&body));
    }

    #[test]
    fn suppresses_workflow_run_for_dependabot_branch() {
        let body = payload(json!({
            "sender": {"login": "github-actions[bot]"},
            "workflow_run": {"head_branch": "dependabot/cargo/serde-1.0.0"}
        }));
        assert!(is_dependabot_event(&body));
    }

    #[test]
    fn does_not_suppress_unrelated_event_that_mentions_dependabot() {
        let body = payload(json!({
            "sender": {"login": "maintainer"},
            "ref": "refs/heads/feature/dependabot-dashboard",
            "issue": {"title": "Document Dependabot"}
        }));
        assert!(!is_dependabot_event(&body));
    }

    #[test]
    fn malformed_payload_is_not_suppressed() {
        assert!(!is_dependabot_event(b"not json"));
    }

    #[test]
    fn suppresses_push_with_skip_marker_in_head_commit() {
        let body = payload(json!({
            "head_commit": {"message": "chore(deps): refresh locks [skip github-alerts]"},
            "commits": []
        }));
        assert!(has_skip_notification_marker(&body));
    }

    #[test]
    fn suppresses_form_encoded_push_with_case_insensitive_marker() {
        let json = json!({
            "head_commit": null,
            "commits": [{"message": "chore(deps): refresh locks [SKIP GITHUB-ALERTS]"}]
        })
        .to_string();
        let body = serde_urlencoded::to_string([("payload", json)]).unwrap();
        assert!(has_skip_notification_marker(body.as_bytes()));
    }

    #[test]
    fn does_not_suppress_push_without_exact_marker() {
        let body = payload(json!({
            "head_commit": {"message": "document skip github alerts behavior"},
            "commits": []
        }));
        assert!(!has_skip_notification_marker(&body));
    }
}
